In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,38,9,8,8,6,85,0,12,34,4565,67,7])
arr2 = np.array([1,2,34,9,8,7,6,5,0,12,34,4565,67,7])

Addtition of two arrays

In [ ]:
result2 = arr1 + arr2
print(result2)

[   2    4   68   18   16   14   12   10    0   24   68 9130  134   14]


Performing substraction on arrays

In [ ]:
result = arr1 - arr2
print(result)
result2 = np.subtract(arr1,arr2)
print(result2)

[ 0  0  4  0  0  1  0 80  0  0  0  0  0  0]
[ 0  0  4  0  0  1  0 80  0  0  0  0  0  0]


Multiplicaiton

In [ ]:
result = arr1 * arr2
print(result)

result = np.multiply(arr1,arr2)
print(result)

[       1        4     1292       81       64       56       36      425
        0      144     1156 20839225     4489       49]
[       1        4     1292       81       64       56       36      425
        0      144     1156 20839225     4489       49]


Devision of an array

In [ ]:
result = arr1 / arr2
print(result)

result = np.divide(arr1,arr2)
print(result)

[ 1.          1.          1.11764706  1.          1.          1.14285714
  1.         17.                 nan  1.          1.          1.
  1.          1.        ]
[ 1.          1.          1.11764706  1.          1.          1.14285714
  1.         17.                 nan  1.          1.          1.
  1.          1.        ]


/tmp/ipykernel_1025/2322342618.py:1: RuntimeWarning: invalid value encountered in divide
  result = arr1 / arr2
/tmp/ipykernel_1025/2322342618.py:4: RuntimeWarning: invalid value encountered in divide
  result = np.divide(arr1,arr2)


Applying power to the array

In [ ]:
result = np.power(arr1,2)
print(result)

[       1        4     1444       81       64       64       36     7225
        0      144     1156 20839225     4489       49]


In [ ]:
result = np.power(arr1,arr2)
print(result)

[                   1                    4  1316572420148035584
            387420489             16777216              2097152
                46656           4437053125                    1
        8916100448256 -5296008294479953920 -2080712387484357883
  8037740809528595931               823543]


Modulos of array

In [ ]:
result = arr1 % 4
print(result)

result = np.mod(arr1,4)
print(result)

[1 2 2 1 0 0 2 1 0 0 2 1 3 3]
[1 2 2 1 0 0 2 1 0 0 2 1 3 3]


Scalar Operations

In [ ]:
arr = np.array([10,20,30])
print(arr + 5)

print(arr * 2)

print(arr / 2)

print(arr ** 2)

[15 25 35]
[20 40 60]
[ 5. 10. 15.]
[100 400 900]


Comparison Operations

In [ ]:
arr = np.array([10,20,30])

result = arr == 20
print(result)

result = arr != 20
print(result)

result = arr > 20
print(result)

result = arr < 20
print(result)

[False  True False]
[ True False  True]
[False False  True]
[ True False False]


In [ ]:
a = np.array([True, False, True])
b = np.array([True, True, False])

print("Logical AND",np.logical_and(a,b))
print("Logical OR",np.logical_or(a,b))

print("Logical NOT",np.logical_not(a))

Logical AND [ True False False]
Logical OR [ True  True  True]
Logical NOT [False  True False]


Aggragator Operations

In [ ]:
print("Sum : ",arr1.sum())
print("Min : ",arr1.min())
print("Max : ",arr1.max())
print("Mean : ",arr1.mean())
print("Median : ",np.median(arr1))
print("Variance : ",np.var(arr1))
print("Standard Deviation : ",np.std(arr1))
print("Correlation Coefficient : ",np.corrcoef(arr1))
print("Product",np.prod(arr1))
print("Cummulative Sum",np.cumsum(arr1))
print("Cummulative Product",np.cumprod(arr1))

Sum :  4842
Min :  0
Max :  4565
Mean :  345.85714285714283
Median :  8.5
Variance :  1369952.9795918367
Standard Deviation :  1170.4499047767217


Absolute Values

In [ ]:
arr = np.array([-10,-20,15])
print(np.abs(arr))

[10 20 15]


In [ ]:
arr = np.array([2.34,4.78,6.12])
# Round -> prev | next
print(np.round(arr))

# Floor -> prev
print(np.floor(arr))

# Ceiling -> next
print(np.ceil(arr))

[2. 5. 6.]
[2. 4. 6.]
[3. 5. 7.]


Matrix Operaitons

In [ ]:
a = np.array([
 [1,2],
 [3,4]
])
b = np.array([
 [5,6],
 [7,8]
])
print(a + b)
print(a * b)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
