In [ ]:
pip install numpy

In [ ]:
import numpy as np

Check Version of the numpy

In [ ]:
print(np.__version__)

2.0.2


Create an array with numpy

In [ ]:
arr = np.array([10,12,23,34,45,21,32,43,54,20,30,40,50])
print(arr)

[10 12 23 34 45 21 32 43 54 20 30 40 50]


create an array with list

In [ ]:
lst = [1,2,3,4,56,7,78,9,90]
arr2 = np.array(lst)

In [ ]:
print(arr2)

[ 1  2  3  4 56  7 78  9 90]


Crate an array with tuple

In [ ]:
data = (12,34,5,6,6,43,7,78,8)
arr3 = np.array(data)
print(arr3)

[12 34  5  6  6 43  7 78  8]


One-Dimensional Array (1D Array)
A 1D array contains only one row

In [ ]:
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


Two-Dimensional Array (2D Array)

In [ ]:
twoDarr = np.array([[1,2,34,5,6,7],[1,2,3,4,5,6]])

In [ ]:
print(twoDarr)

[[ 1  2 34  5  6  7]
 [ 1  2  3  4  5  6]]


Three Dimensional Array

In [ ]:
arr = np.array([
 [
 [1,2,3],
 [3,4,3]
 ],
 [
 [5,6,3],
 [7,83,3]
 ]
])

In [ ]:
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Checking dimensions of the array

In [ ]:
print(twoDarr.ndim)

2


Checking the shape of an array

In [ ]:
print(arr.shape)

(2, 2, 3)


Size of an array

In [ ]:
print(arr.size)

12


checking the data type of an array

In [ ]:
print(arr.dtype)

int64


Creating an array with specific data type

In [ ]:
arr = np.array([1,2,3],dtype=float)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64
